### ISSUE TITLE
Reset UL and LI element margins for integration with Calcite

### ISSUE THREAD

**Issue by mpriour** [Esri/global-nav#87]
Calcite web adds some pretty significant margins to `ul` and `li` elements. At the beginning of global-nav css we should reset those margins to zero for those elements so that this looks correct in apps that use Calcite web without needed specific overwrites in each app. Such as:

```css
.esri-header ul, .esri-header li, .esri-footer ul, .esri-footer li {
    margin: 0;
}
```
